import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import About from "~/components/landing/About";
import RecentPosts from "~/components/landing/RecentPosts";
import Hero from "~/components/landing/Hero";
import type { blogItem } from "~/common/types";

const dummyBlogPosts: blogItem[] = [
	{
		slug: "getting-started-with-react",
		title: "Getting Started with React",
		desc: "Learn how to get started with React and build your first app.",
		date: "2022-11-15",
		tags: ["React", "JavaScript", "Web Development"],
		image: "https://images.velog.io/images/azurestefan/post/6b52f504-13be-4530-98ff-b8d0d5daecf0/react.png",
	},
	{
		slug: "10-tips-for-better-coding",
		title: "10 Tips for Better Coding",
		desc: "Improve your coding skills with these helpful tips and tricks.",
		date: "2022-10-28",
		tags: ["Coding", "Software Development", "Best Practices"],
		image: "https://c0.wallpaperflare.com/preview/111/43/764/code-coder-codes-coding-thumbnail.jpg",
	},
	{
		slug: "what-is-artificial-intelligence",
		title: "What is Artificial Intelligence?",
		desc: "Get an overview of artificial intelligence and its applications.",
		date: "2022-09-03",
		tags: ["Artificial Intelligence", "Machine Learning", "Technology"],
		image: "https://rhombus.com/img/r2-security-cameras-ai-edge.jpg",
	},
	{
		slug: "building-a-restful-api-with-node-js",
		title: "Building a RESTful API with Node.js",
		desc: "Learn how to build a RESTful API using Node.js and Express.",
		date: "2022-08-12",
		tags: ["Node.js", "API", "Web Development"],
		image: "https://cdn.codeforgeek.com/wp-content/uploads/2023/01/What-is-Node.js-Thumbnail-2.png",
	},
	{
		slug: "introduction-to-cybersecurity",
		title: "Introduction to Cybersecurity",
		desc: "Learn the basics of cybersecurity and how to protect your digital assets.",
		date: "2022-07-01",
		tags: ["Cybersecurity", "Information Security", "Technology"],
		image: "https://www.wplgroup.com/aci/wp-content/uploads/sites/2/2017/06/Cyber-Security-Thumbnail.jpg",
	},
];

const Home: NextPage = () => {
	const [postsToRender, setPostsToRender] = useState<blogItem[]>([]);

	useEffect(() => {
		const getPosts = async () => {
			const res = await fetch("/api/getPosts");
			const data = await res.json();
			console.log("data: ", data);
			setPostsToRender(data);
		};
		getPosts();
	}, []);

	return (
		<div className="bg-stone-900">
			<Head>
				<title>My Cool Portfolio</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<About />
			<RecentPosts blogPostsToDisplay={postsToRender} />
		</div>
	);
};

export default Home;
